project:
  type: website
  resources: images
  output-dir: docs

website:
  navbar: false

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: false
    include-before-body: radar-header.html
    
execute:
  freeze: auto